server:
  port: 8888

info:
  app:
    version: "@project.version@"

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fabricio-entringer/spring-cloud-config-lab
          search-paths: config-repo/{application}/{profile}
          default-label: master
          clone-on-start: true
        native:
          search-locations: classpath:/,file:./config-repo/{application}/{profile}
  security:
    user:
      name: admin
      password: config-server-password
  profiles:
    active: native  # Use native profile for local development

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    org.springframework.cloud.config: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: qa